In [4]:
import os
import numpy as np
import tensorflow as tf
from caffe_classes import class_names

In [3]:
t1 = [1,2,3]
t2 = [4,5,6]
t3=tf.concat([t1,t2], axis=0)

In [4]:
print(t3)

Tensor("concat:0", shape=(6,), dtype=int32)


In [26]:
output = [0.6, 0.0, 0.2, 1.0]
ground_truth = [1.0, 1.0, 0.0, 1.0]
predicted_class = tf.greater(output, 0.5)
correct = tf.equal(predicted_class, tf.equal(ground_truth,1.0))
accuracy = tf.reduce_mean( tf.cast(correct, 'float'))
sess = tf.Session()
print(sess.run(accuracy))

0.75


In [30]:
a = np.array([1, 2])
x=np.copy(a)
print(x)

[1 2]


In [37]:
y=[0,0,0,1,1,1]
np.array(y).reshape((-1, 1))

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1]])

In [43]:
from tensorflow.python.tools import inspect_checkpoint as chkp
chkp.print_tensors_in_checkpoint_file("./tmp/model_whole.ckpt", tensor_name='', all_tensor_names='', all_tensors=True)

tensor_name:  Variable
[[[[-2.83153467e-02 -7.19704404e-02  3.78898042e-03 ... -6.75531849e-03
     1.57427334e-03 -7.34161213e-03]
   [ 8.39668140e-03 -6.77743629e-02 -4.38617989e-02 ...  3.69289308e-03
    -2.12163124e-02  2.08328497e-02]
   [-6.01018872e-03 -3.69863659e-02  3.24545279e-02 ...  1.04015123e-03
    -1.75325349e-02 -1.08853113e-02]]

  [[-6.76262565e-03 -9.85573977e-02  2.73596449e-03 ... -4.93216841e-03
    -4.97266697e-03 -1.09553523e-02]
   [ 3.13869417e-02 -9.95327160e-02 -3.94608229e-02 ...  8.02036002e-03
    -2.56089102e-02  1.36672202e-02]
   [ 1.04832407e-02 -6.84838146e-02  4.58296984e-02 ...  5.48922690e-04
    -1.75612103e-02 -8.77811201e-03]]

  [[ 1.69464536e-02 -1.14213303e-01 -1.37726509e-03 ... -8.87093227e-03
    -8.55328236e-03  1.48361339e-03]
   [ 2.52514854e-02 -1.22040361e-01 -3.44707184e-02 ... -5.47534972e-03
    -2.93933377e-02  1.74788758e-02]
   [-2.10042596e-02 -9.43751261e-02  7.03385398e-02 ... -5.53181535e-03
    -2.22472325e-02 -5.038722

[[-0.00433848 -0.00716358 -0.00672231 ... -0.00185999 -0.00616173
  -0.00336802]
 [-0.00273971 -0.0073863   0.01227041 ... -0.00323482  0.00020631
  -0.00540252]
 [-0.00503064  0.00243913  0.00136081 ... -0.00143727  0.00729038
  -0.00344706]
 ...
 [-0.00949919 -0.00647061 -0.001888   ...  0.0021475   0.00136053
   0.0170434 ]
 [ 0.00203296  0.00029484  0.00065279 ...  0.00071566 -0.00333344
  -0.00376848]
 [ 0.01293693  0.0024846   0.00790328 ...  0.00487464 -0.00440114
   0.00766999]]
tensor_name:  Variable_11
[0.10706235 0.04205888 0.0946017  ... 0.14076257 0.12524039 0.18391114]
tensor_name:  Variable_12
[[[[-2.83153467e-02 -7.19704404e-02  3.78898042e-03 ... -6.75531849e-03
     1.57427334e-03 -7.34161213e-03]
   [ 8.39668140e-03 -6.77743629e-02 -4.38617989e-02 ...  3.69289308e-03
    -2.12163124e-02  2.08328497e-02]
   [-6.01018872e-03 -3.69863659e-02  3.24545279e-02 ...  1.04015123e-03
    -1.75325349e-02 -1.08853113e-02]]

  [[-6.76262565e-03 -9.85573977e-02  2.73596449e-03 ...

[[-0.00433848 -0.00716358 -0.00672231 ... -0.00185999 -0.00616173
  -0.00336802]
 [-0.00273971 -0.0073863   0.01227041 ... -0.00323482  0.00020631
  -0.00540252]
 [-0.00503064  0.00243913  0.00136081 ... -0.00143727  0.00729038
  -0.00344706]
 ...
 [-0.00949919 -0.00647061 -0.001888   ...  0.0021475   0.00136053
   0.0170434 ]
 [ 0.00203296  0.00029484  0.00065279 ...  0.00071566 -0.00333344
  -0.00376848]
 [ 0.01293693  0.0024846   0.00790328 ...  0.00487464 -0.00440114
   0.00766999]]
tensor_name:  Variable_23
[0.10706235 0.04205888 0.0946017  ... 0.14076257 0.12524039 0.18391114]
tensor_name:  Variable_3
[0.05534449 0.09121124 0.07707409 0.11000117 0.07325118 0.10361461
 0.10486514 0.08514547 0.0912852  0.10794014 0.10396023 0.06569654
 0.09436901 0.10802913 0.11602841 0.06944368 0.09787809 0.0990192
 0.10209256 0.06280151 0.10227942 0.08824021 0.08725776 0.09234343
 0.08496449 0.10332887 0.06412431 0.09248152 0.1199058  0.10202472
 0.08313854 0.05219192 0.08901248 0.07199872 0.0866

[[ 1.9628284e-02 -1.2769865e-02 -1.6311960e-02 ...  1.5918415e-02
  -1.4909714e-02  1.8525583e-03]
 [ 1.8128527e-02  2.4801339e-03  2.0101445e-02 ...  1.4514787e-02
  -1.0183983e-02  1.1165362e-02]
 [ 1.5694235e-02 -3.8599656e-03 -1.3602432e-02 ... -7.0739565e-03
  -8.7409737e-03 -1.6340407e-02]
 ...
 [ 1.1029701e-02  1.5408568e-02 -1.2279982e-02 ... -4.3800580e-03
   5.7734665e-03  1.7879050e-02]
 [-1.2219943e-02 -4.3391134e-05 -1.3565375e-02 ...  3.0208100e-03
  -6.4668804e-04 -1.1954198e-02]
 [-7.4489741e-04 -1.1052360e-02 -1.5741967e-02 ...  8.4410515e-03
  -1.7976280e-02 -9.4271246e-03]]
tensor_name:  dense/kernel/Adam
[[-2.4571007e-03  3.9092936e-03 -4.3290734e-04 ... -1.4192457e-04
   3.9119978e-04  3.0324035e-03]
 [-2.2816411e-03  1.0218151e-03 -8.8019774e-04 ... -6.3000520e-04
   5.8787660e-04  1.2325814e-03]
 [-1.7252518e-04  3.3687979e-06  0.0000000e+00 ...  0.0000000e+00
   0.0000000e+00  2.0519897e-06]
 ...
 [-2.3238172e-03  2.1294162e-03  0.0000000e+00 ... -1.9061312e-05


In [17]:
xx = np.array([-5.0, 0.5, 10.0]).reshape((-1, 1))
yy = np.array([1.0, 0.0, 0.0]).reshape((-1, 1))
x = tf.placeholder(tf.float32, [3, 1])
y = tf.placeholder(tf.float32, [3, 1])
loss = tf.losses.mean_squared_error(predictions=x, labels=y)
temp = tf.sigmoid(x)
with tf.Session() as sess:
    print(loss.eval(feed_dict={x:xx, y:yy}))
    print(temp.eval(feed_dict={x:xx, y:yy}))

45.416668
[[0.00669285]
 [0.62245935]
 [0.9999546 ]]
